In [1]:
#from urllib.request import urlopen,Request
import requests
import json
import pandas as pd
import matplotlib.pyplot as plt
from geopy.geocoders import Nominatim

#geopy.geocoders.options.default_user_agent = "my-application"
geolocator = Nominatim(user_agent="my-application") #create object
places = ["raleigh", "durham", "RTP"] 
# login on meetup.com. if you dont have an account, then please signup
# Go to https://secure.meetup.com/meetup_api/console/?path=/2/groups
# In the topics like "Python", enter topic of your choice. and click on show response
# copy the signed key. in the singed key, copy the sig_id and sig and initialise variables sig_id and sig
# sample signed key : "https://api.meetup.com/2/groups?offset=0&format=json&topic=python&photo-host=public&page=20&radius=25.0&fields=&order=id&desc=false&sig_id=******&sig=*****************"
urls = [] #url lists
radius = 25.0 #add the radius in miles
data_format = "json" #you can add another format like XML
topics = ["Python", "Analysts"] #add your choice of topic here
sig_id = "285943115" # initialise with your sign id, check sample signed key
sig = "db8c40f0ee987982890eb5200b288e22bdecd403" # initialise with your sign, check sample signed key

for place in places: 
 location = geolocator.geocode(place)
 for topic in topics:
  urls.append("https://api.meetup.com/2/groups?offset=0&format=" 
             + data_format + "&lon=" + str(location.longitude) 
             + "&topic=" + topic + "&photo-host=public&page=500&radius=" 
             + str(radius)+"&fields=&lat=" + str(location.latitude) 
             + "&order=id&desc=false&sig_id=" +sig_id + "&sig=" + sig)

In [2]:
data = []
for url in urls:
    response = requests.get(url)
    json_dict = response.json()
    if 'results' in json_dict.keys():
        data.append(json_dict)
for datum in data:
    datum = datum['results']
    if len(datum) > 0:
        name = [i['name'] for i in datum]
        rating = [i['rating'] for i in datum]
        members = [i['members'] for i in datum]
        city = [i['city'] for i in datum]
                                
df1 = pd.DataFrame([name,rating,members,city])
df = pd.DataFrame([name,rating,members,city]).T
df.columns = ['name','rating','members','city'] 
df = df.sort_values(['rating'],ascending=False)
df

                                              name rating members     city
8                                RTP Python Meetup      5     757  Raleigh
5                    Women Who Code Raleigh Durham   4.95    1024  Raleigh
7                                Deep Learning RTP   4.94    1234   Durham
3                                     PyLadies RDU   4.93     430  Raleigh
0   Triangle Python Users Group (formerly TriZPUG)   4.89    1298   Durham
2                            Triangle Hacker Hours   4.76     683   Durham
10                Learn to Code | Thinkful Raleigh   4.75    1122  Raleigh
1                                             RIoT   4.56    5440  Raleigh
4                          Raleigh Cassandra Users      0     140  Raleigh
6                                          TriSalt      0      72   Durham
9                             Cary Code and Coffee      0     255     Cary
11                           Programming In Public      0      50     Cary
12                                 Data Science NC      0     164  Raleigh